---
title       : Next Word Prediction using NLP
subtitle    : Building a word predictor using Natural Language Processing in R
author      : Telvis Calhoun
job         : technicalelvis.com
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      #
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Goals

- Build a language model using blog, news and twitter text provided by [Data Science Capstone Course](https://www.coursera.org/learn/data-science-project/home/welcome).
- Use this language model to predict the next word as a user types - similar to the [Swiftkey text messaging app](https://swiftkey.com/en) 
- Create a word predictor demo using [R and Shiny](http://shiny.rstudio.com/).

--- .class #id

## Word Prediction using N-Grams
Assume the training data shows the frequency of "data" is 198, "data entry" is 12 and "data streams" is 10. We calculate the [maximum likelihood estimate](https://en.wikipedia.org/wiki/Maximum_likelihood) (MLE) as:

The probability of "data entry":

$$
P_{mle}(entry|data) = \frac{12}{198} = 0.06 = 6\%
$$

The probability of "data streams" is:
$$
P_{mle}(streams|data) = \frac{10}{198} = 0.05 = 5\%
$$

If the user types, "data", the model predicts that "entry" is the most likely next word.

--- .class #id


## Modeling
1. Generate 2-grams, 3-grams and 4-grams.
2. Select n-grams that account for 66% of word instances. This reduces the size of the models.
3. Calculate the maximum likelihood estimate (MLE) for words for each model.

## Prediction
1. Load the ngram models
2. Tokenize and preprocess user input.
3. Implement [stupid backoff](http://www.aclweb.org/anthology/D07-1090.pdf) starting on 4-gram model backing off to 3-gram model backing off to 2-gram model.
4. Return 3 words with largest MLE


--- .class #id


## Demo Application

- [Click here to try the Shiny App that demonstrates the recommender!](https://technicalelvis.shinyapps.io/shiny_demo_word_predictor/)

```{r fig.width=10, fig.height=7, fig.align="center", echo=FALSE}
library(png)
library(grid)
img <- readPNG("./images/shiny_app_screen_shot.png")
grid.raster(img)
```
